version: "3.9"
services:
  psql:
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - sqldata:/var/lib/postgresql/data
      - ./psql:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD="${REDIS_PASSWORD}"
    restart: on-failure
    ports:
      - "${REDIS_PORT}:6379"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - /data/redis

volumes:
  sqldata:
